name: mcp-example
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - fastapi==0.116.1
    - uvicorn==0.35.0
    - streamlit==1.49.1
    - langchain==0.3.27
    - langgraph==0.6.7
    - langchain-openai==0.3.33
    - python-dotenv==1.1.1
    - httpx==1.0.1
    - fastmcp==2.11
    - mcp==1.13.1
    - langchain-mcp-adapter==0.1.9
    - pydantic==2.11.9
